name: Compile Examples
on:
  - push
  - pull_request

jobs:
  build-avr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fqbn:
          - arduino:avr:uno
          - arduino:avr:nano:cpu=atmega168
          - arduino:avr:nano:cpu=atmega328
          - arduino:avr:mega:cpu=atmega1280
          - arduino:avr:mega:cpu=atmega2560
          - arduino:avr:leonardo
          - arduino:megaavr:uno2018:mode=on
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          sketch-paths: |
            - examples/PlotPlus
            - examples/PlotPlusConfig
            - examples/PlotPlusWith
            - examples/SimPlot

  build-nonavr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fqbn:
          - arduino:samd:nano_33_iot
          - arduino:mbed:nano33ble
          - arduino:mbed_nano:nanorp2040connect
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          sketch-paths: |
            - examples/PlotPlus
            - examples/SimPlot
          
  build-esp32:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fqbn:
          - esp32:esp32:esp32
          - esp32:esp32:esp32s3
          - esp32:esp32:esp32c3
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          sketch-paths: |
            - examples/PlotPlus
            - examples/SimPlot
          cli-compile-flags: |
            - --warnings="none"
          libraries: |
            - source-path: ./
            - name: EspSoftwareSerial

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          compliance: specification
